on:
  push:
    branches:
      - test
    paths-ignore:
      - "README.md"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      # - name: Create and populate application.properties
      #   run: |
      #     touch ./src/main/resources/application-dev.yml
      #     echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-dev.yml

      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew

      # - name: Refresh dependencies
      #   run: ./gradlew --refresh-dependencies

      # - name: Clean and build without tests
      #   run: ./gradlew clean build -x test

      # - name: List built files
      #   run: ls -al ./build/libs/

      # - name: Add EC2 host to known_hosts
      #   env:
      #     EC2_HOST: ${{ secrets.EC2_HOST }}
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

      # - name: Create pem file
      #   env:
      #     EC2_KEY: ${{ secrets.EC2_KEY }}
      #   run: |
      #     printf '%s' "$EC2_KEY" > ec2.pem
      #     chmod 400 ec2.pem

      # - name: Transfer Jar to EC2
      #   env:
      #     EC2_HOST: ${{ secrets.EC2_HOST }}
      #     EC2_USER: ${{ secrets.EC2_USER }}
      #     APP_NAME: ${{ secrets.APP_NAME }}
      #   run: |
      #     scp -i ec2.pem ./build/libs/$APP_NAME $EC2_USER@$EC2_HOST:~/

      - name: Run Jar on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            PID=$(lsof -t -i:8080)
            if [ ! -z "$PID" ]; then
              kill -9 $PID
            fi
            nohup java -jar ${{ secrets.APP_NAME }} > app.log 2>&1 &

# pkill -f "java -jar ${{ secrets.APP_NAME }}" || true
