on:
  push:
    branches:
      - test
    paths-ignore:
      - "README.md"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create and populate application.properties
        run: |
          touch ./src/main/resources/application-dev.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-dev.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Refresh dependencies
        run: ./gradlew --refresh-dependencies

      - name: Clean and build without tests
        run: ./gradlew clean build -x test

      - name: List built files
        run: ls -al ./build/libs/

      - name: Transfer Jar to EC2
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: |
          scp -i "$EC2_KEY" ./build/libs/$APP_NAME "$EC2_USER"@"$EC2_HOST":~/

      - name: Run Jar on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f "java -jar ${{ secrets.APP_NAME }}" || true
            nohup java -jar ${{ secrets.APP_NAME }}
